// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa27VtZhooJ0-GcwAg_ynFAYthB-3tByM',
    appId: '1:592696191016:web:f19143adee516c333fad1d',
    messagingSenderId: '592696191016',
    projectId: 'dating-app-7421f',
    authDomain: 'dating-app-7421f.firebaseapp.com',
    storageBucket: 'dating-app-7421f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyy2YSbmC7fbyRe4qL2pRJILTqv_WIG58',
    appId: '1:592696191016:android:d5e59765f4fd26c33fad1d',
    messagingSenderId: '592696191016',
    projectId: 'dating-app-7421f',
    storageBucket: 'dating-app-7421f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzegozF22MfSe75QEbtE7t7q96DoYfjAY',
    appId: '1:592696191016:ios:d4702a285b041a333fad1d',
    messagingSenderId: '592696191016',
    projectId: 'dating-app-7421f',
    storageBucket: 'dating-app-7421f.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzegozF22MfSe75QEbtE7t7q96DoYfjAY',
    appId: '1:592696191016:ios:e612236bce9b52e13fad1d',
    messagingSenderId: '592696191016',
    projectId: 'dating-app-7421f',
    storageBucket: 'dating-app-7421f.appspot.com',
    iosBundleId: 'com.example.datingApp.RunnerTests',
  );
}
